"""testing

Revision ID: da94ee91199b
Revises: 20260523_0001
Create Date: 2026-05-23 03:04:47.573044
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'da94ee91199b'
down_revision: Union[str, Sequence[str], None] = '20260523_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
